######################################################################
# Automatically generated by qmake (2.01a) Tue Jul 17 18:14:46 2007
######################################################################

TEMPLATE = app
TARGET = qshowpost
DEPENDPATH += .
INCLUDEPATH += .
QT += core 
QT -= gui


# Input
SOURCES += main.cpp
